language: node_js
node_js:
- node
script: npm run lint
deploy:
  provider: heroku
  app: cs411-attendance
  api_key:
    secure: 2W+yCdKp9cjZCS1wyplJxQZ2PVnTFDZdGOqvN/aXKoCdmUve/7AlLlh1e2ibZJ9RzGtmsouP5lWSQVuzsK4DucR+3/FnX/2vNGRYwhGIM8PokxsWBdi7el9DteajXUTbjGPBWyw5jru5cvbUQTE+dadamVFdS4cXub/N0QBNxJA8fbVEfr/DIwjBmJae0M6vPewzBjAxvrlCZynCvxGwelday3uthD19V9yVuD3klSwHCw+dvzWAQ49X8vpk1Z7yrAgAH4rbOEZtc2in1Q3QU0YUBgBHhEt51PScMmExA7IqXmVXyZwB7Wg9IaKYZS7uHTBliHWYRW8gra7uo9XescnPjPC4MIdfzAx/q+61oqXE560RH2ycwVXngYd7vyN1ip0KLB0TUcIqOeuIjQ215GA9PBNXvjbxsuB6rbWtZpyYfDNVFzJ9OboRce11m73Vc64sSNjDWTmh+rzIxndn8uK2nlQzNanwpz9KfphSB84Pxyt0lTHYnldA5RVrHaKi8Ru4TQyQzd75QPb92ry5Sb96Lu3hACes692AT8pnVfSZUGeKQ+Nb66jCV00IdMbPW+BxOZ0MXiS4WSdLbrJ4SKCdyxh6uR4HKjZ8och01n/VElCj8AD62PXSygHlbiFbH5K0BAFzs+hKiuqil4bG2T5CLvrrPgrcUaL7j/N8Rro=
